"""CLI: print every chapter's box numbers with provenance; regenerate derived files."""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
from pathlib import Path

from . import CHAPTERS, TEX, available, load
from .common import ERAS, CircuitStatus, Provenance, Tagged, close, fmt_range
from .groups import GROUPS, conflicts

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent


def _assumption_rows(a) -> list[tuple[str, str, str, str]]:
    rows = []
    for f in dataclasses.fields(a):
        v = getattr(a, f.name)
        if isinstance(v, Tagged):
            rows.append((f.name, fmt_range((v.lo, v.hi)) if v.is_range else str(v.value),
                         v.prov.value, v.src or v.note))
        else:
            rows.append((f.name, str(v), "-", ""))
    return rows


def table(chapters: list[int], show_inputs: bool) -> str:
    out = []
    for ch in chapters:
        m = load(ch)
        a = m.Assumptions()
        out.append(f"\n== Ch. {ch}  {CHAPTERS[ch]}  ({TEX[ch]}) ==")
        if show_inputs:
            for name, val, prov, src in _assumption_rows(a):
                out.append(f"   {name:28s} {val:>16s}  [{prov:18s}] {src}")
        for era in ERAS:
            if era not in m.PUBLISHED:
                continue
            r = m.model(a, era)
            p = m.PUBLISHED[era]
            ok_lq = close(r.lq, p.lq, p.rel_tol)
            ok_t = p.hard_ops is None or close(r.hard_ops, p.hard_ops, p.rel_tol)
            flag = "ok " if (ok_lq and ok_t) else "MISMATCH"
            out.append(f"   {era:9s} LQ {fmt_range(r.lq):>12s} (pub {fmt_range(p.lq):>12s})"
                       f"   T {fmt_range(r.hard_ops):>16s} (pub {fmt_range(p.hard_ops):>16s})   {flag}")
            if r.breakdown:
                bt = r.breakdown_total()
                out.append(f"             breakdown sums to {bt:.3g} T "
                           f"({', '.join(f'{q.name}:{q.t_total:.2g}' for q in r.breakdown)})")
    return "\n".join(out)


def resources_json(chapters: list[int]) -> dict:
    """The INSTANCES shape resources.py expects, generated instead of hand-kept."""
    inst = []
    for ch in chapters:
        m = load(ch)
        a = m.Assumptions()
        for era in ERAS:
            if era not in m.PUBLISHED:
                continue
            r = m.model(a, era)
            for lbl, lq, t, extra in getattr(m, "INSTANCE_ROWS", lambda a, era, r: [])(a, era, r):
                row = dict(ch=ch, era=era, label=lbl, lq=list(lq), t=list(t),
                           codesign=(era == "codesign"), src=m.PUBLISHED[era].src)
                # a chapter's extras may repeat a core key (e.g. Ch. 8 mirrors resources.py's
                # defaults) only if they agree; a silent override would hide a mislabelled row
                for k, v in extra.items():
                    if k in row and v != row[k]:
                        raise ValueError(f"Ch{ch} {era} {lbl!r}: INSTANCE_ROWS extra {k}={v!r} "
                                         f"conflicts with the generated {row[k]!r}")
                row.update(extra)
                inst.append(row)
    return {"instances": inst, "generated_by": "python -m estimates --resources"}


def circuit_status_md(chapters: list[int]) -> str:
    lines = ["# Circuit-knowledge status", "",
             "Generated by `python -m estimates --status`. For every primitive that enters a",
             "chapter's hard-op count: whether an explicit gate-level circuit exists (COMPILED),",
             "or the number rests on a counting argument (SCALING), a conjecture (CONJECTURE),",
             "or has no stated origin (UNSOURCED). The non-COMPILED rows are what would have",
             "to be compiled before any of these estimates could be handed to a logical-circuit",
             "tool such as QLX.", ""]
    totals = {s: 0 for s in CircuitStatus}
    for ch in chapters:
        m = load(ch)
        a = m.Assumptions()
        lines.append(f"## Ch. {ch} — {CHAPTERS[ch]}")
        lines.append("")
        lines.append("| era | primitive | count | T each | T total | status | source | note |")
        lines.append("|---|---|---|---|---|---|---|---|")
        cnt = {s: 0 for s in CircuitStatus}
        for era in ERAS:
            if era not in m.PUBLISHED:
                continue
            for p in m.model(a, era).breakdown:
                cnt[p.status] += 1
                lines.append(f"| {era} | {p.name} | {p.count:.3g} | {p.t_each:.3g} | {p.t_total:.3g} "
                             f"| **{p.status.value}** | {p.src} | {p.note} |")
        lines.append("")
        lines.append("  ".join(f"{s.value}: {cnt[s]}" for s in CircuitStatus))
        lines.append("")
        for s in CircuitStatus:
            totals[s] += cnt[s]
    lines.append("## Gauge-group link widths")
    lines.append("")
    for k, chw, cw in conflicts():
        lines.append(f"- **{k}**: chapter uses {chw} qubits/link, compiled circuits use {cw} "
                     f"({GROUPS[k].link_qubits_compiled.src}) — unreconciled")
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    lines.append("  ".join(f"{s.value}: {totals[s]}" for s in CircuitStatus))
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(prog="estimates")
    ap.add_argument("--resources", action="store_true", help="write resources.json")
    ap.add_argument("--status", action="store_true", help="write CIRCUIT_STATUS.md")
    ap.add_argument("--inputs", action="store_true", help="show every assumption with provenance")
    ap.add_argument("--ch", type=int, nargs="*", help="restrict to chapters")
    args = ap.parse_args(argv)
    chapters = args.ch or available()
    missing = [c for c in CHAPTERS if c not in chapters]
    if missing and not args.ch:
        print(f"(no model yet for chapters {missing})", file=sys.stderr)
    if args.resources:
        p = SCRIPTS / "resources.json"
        p.write_text(json.dumps(resources_json(chapters), indent=1))
        print(f"wrote {p}")
        return
    if args.status:
        p = HERE / "CIRCUIT_STATUS.md"
        p.write_text(circuit_status_md(chapters))
        print(f"wrote {p}")
        return
    print(table(chapters, args.inputs))


if __name__ == "__main__":
    main()
