"""CLI: print every chapter's box numbers with provenance; regenerate derived files."""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
from pathlib import Path

from . import CHAPTERS, TEX, available, load
from .common import DEPTH_EXPORTS, ERAS, CircuitStatus, Provenance, Tagged, close, fmt_range
from .groups import GROUPS, conflicts

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
# Where the derived files are written. resources.json sits in the package's parent directory in
# both layouts (the paper's scripts/ or the repository root). CIRCUIT_STATUS.md sits beside the
# package in the paper tree (scripts/estimates/) and under docs/ in the standalone repository.
DOCS = SCRIPTS / "docs" if (SCRIPTS / "docs").is_dir() else HERE


def _tagged_value(v: Tagged) -> str:
    """A numeric (lo, hi) prints as a band; anything else (a number, a string, a tuple of
    strings such as a pair of route names) prints as is."""
    if v.is_range and len(v.value) == 2 and all(isinstance(x, (int, float)) for x in v.value):
        return fmt_range((v.lo, v.hi))
    return str(v.value)


def _assumption_rows(a) -> list[tuple[str, str, str, str]]:
    rows = []
    for f in dataclasses.fields(a):
        v = getattr(a, f.name)
        if isinstance(v, Tagged):
            rows.append((f.name, _tagged_value(v), v.prov.value, v.src or v.note))
        else:
            rows.append((f.name, str(v), "-", ""))
    return rows


def table(chapters: list[int], show_inputs: bool) -> str:
    out = []
    for ch in chapters:
        m = load(ch)
        a = m.Assumptions()
        out.append(f"\n== Ch. {ch}  {CHAPTERS[ch]}  ({TEX[ch]}) ==")
        if show_inputs:
            for name, val, prov, src in _assumption_rows(a):
                out.append(f"   {name:28s} {val:>16s}  [{prov:18s}] {src}")
        for era in ERAS:
            if era not in m.PUBLISHED:
                continue
            r = m.model(a, era)
            p = m.PUBLISHED[era]
            ok_lq = close(r.lq, p.lq, p.rel_tol)
            ok_t = p.hard_ops is None or close(r.hard_ops, p.hard_ops, p.rel_tol)
            flag = "ok " if (ok_lq and ok_t) else "MISMATCH"
            out.append(f"   {era:9s} LQ {fmt_range(r.lq):>12s} (pub {fmt_range(p.lq):>12s})"
                       f"   T {fmt_range(r.hard_ops):>16s} (pub {fmt_range(p.hard_ops):>16s})   {flag}")
            if r.breakdown:
                bt = r.breakdown_total()
                out.append(f"             breakdown sums to {bt:.3g} T "
                           f"({', '.join(f'{q.name}:{q.t_total:.2g}' for q in r.breakdown)})")
    return "\n".join(out)


def resources_json(chapters: list[int]) -> dict:
    """The INSTANCES shape resources.py expects, generated instead of hand-kept."""
    inst = []
    for ch in chapters:
        m = load(ch)
        a = m.Assumptions()
        for era in ERAS:
            if era not in m.PUBLISHED:
                continue
            r = m.model(a, era)
            for lbl, lq, t, extra in getattr(m, "INSTANCE_ROWS", lambda a, era, r: [])(a, era, r):
                row = dict(ch=ch, era=era, label=lbl, lq=list(lq), t=list(t),
                           codesign=(era == "codesign"), src=m.PUBLISHED[era].src)
                # a chapter's extras may repeat a core key (e.g. Ch. 8 mirrors resources.py's
                # defaults) only if they agree; a silent override would hide a mislabelled row
                for k, v in extra.items():
                    if k in row and v != row[k]:
                        raise ValueError(f"Ch{ch} {era} {lbl!r}: INSTANCE_ROWS extra {k}={v!r} "
                                         f"conflicts with the generated {row[k]!r}")
                row.update(extra)
                inst.append(row)
    return {"instances": inst, "generated_by": "python -m estimates --resources"}


def circuit_status_md(chapters: list[int]) -> str:
    lines = ["# Circuit-knowledge status", "",
             "Generated by `python -m estimates --status`. For every primitive that enters a",
             "chapter's hard-op count: whether an explicit gate-level circuit exists (COMPILED),",
             "or the number rests on a counting argument (SCALING), a conjecture (CONJECTURE),",
             "or has no stated origin (UNSOURCED). The non-COMPILED rows are what would have",
             "to be compiled before any of these estimates could be handed to a logical-circuit",
             "tool such as QLX.", ""]
    totals = {s: 0 for s in CircuitStatus}
    for ch in chapters:
        m = load(ch)
        a = m.Assumptions()
        lines.append(f"## Ch. {ch} — {CHAPTERS[ch]}")
        lines.append("")
        lines.append("| era | primitive | count | T each | T total | status | source | note |")
        lines.append("|---|---|---|---|---|---|---|---|")
        cnt = {s: 0 for s in CircuitStatus}
        for era in ERAS:
            if era not in m.PUBLISHED:
                continue
            for p in m.model(a, era).breakdown:
                cnt[p.status] += 1
                lines.append(f"| {era} | {p.name} | {p.count:.3g} | {p.t_each:.3g} | {p.t_total:.3g} "
                             f"| **{p.status.value}** | {p.src} | {p.note} |")
        lines.append("")
        lines.append("  ".join(f"{s.value}: {cnt[s]}" for s in CircuitStatus))
        lines.append("")
        for s in CircuitStatus:
            totals[s] += cnt[s]
    lines.append("## Gauge-group link widths")
    lines.append("")
    for k, chw, cw in conflicts():
        lines.append(f"- **{k}**: chapter uses {chw} qubits/link, compiled circuits use {cw} "
                     f"({GROUPS[k].link_qubits_compiled.src}) — unreconciled")
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    lines.append("  ".join(f"{s.value}: {totals[s]}" for s in CircuitStatus))
    return "\n".join(lines) + "\n"


def _chapter_arg(s: str) -> int:
    """'ch03', 'CH3' or '3' -> 3."""
    t = s.strip().lower()
    if t.startswith("ch"):
        t = t[2:]
    try:
        ch = int(t)
    except ValueError:
        raise argparse.ArgumentTypeError(f"{s!r} is not a chapter; use chNN, e.g. ch03")
    if ch not in CHAPTERS:
        raise argparse.ArgumentTypeError(f"no model for chapter {ch}; chapters are {sorted(CHAPTERS)}")
    return ch


def _val(v) -> str:
    """One number, a (lo, hi) band, a Tagged value or None, as the chapter report prints it."""
    if v is None:
        return "-"
    if isinstance(v, Tagged):
        return _tagged_value(v)
    if isinstance(v, (tuple, list)) and len(v) == 2 and all(isinstance(x, (int, float)) for x in v):
        return fmt_range(tuple(v))
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


def chapter_report(ch: int, show_intermediates: bool = False) -> str:
    """One chapter: its assumptions with provenance, its resources.json rows, and the per-era
    exports (headline against the box, shots, wall, epsilon_l, the CONTRACT.md rule-12 keys and
    the primitive breakdown). Read-only: it recomputes the model and writes nothing."""
    m = load(ch)
    a = m.Assumptions()
    results = {era: m.model(a, era) for era in ERAS if era in m.PUBLISHED}
    rows_fn = getattr(m, "INSTANCE_ROWS", lambda a, era, r: [])
    out = [f"Ch. {ch}  {CHAPTERS[ch]}  ({TEX[ch]})", ""]

    rows = _assumption_rows(a)
    counts = {p.value: 0 for p in Provenance}
    for _, _, prov, _ in rows:
        if prov in counts:
            counts[prov] += 1
    out.append(f"ASSUMPTIONS  ({len(rows)} fields: "
               + ", ".join(f"{k} {n}" for k, n in counts.items() if n) + ")")
    for name, val, prov, src in rows:
        out.append(f"   {name:38s} {val:>18s}  [{prov:18s}] {src}")
    out.append("")

    out.append("INSTANCES  (the rows this chapter writes to resources.json)")
    for era, r in results.items():
        for lbl, lq, t, extra in rows_fn(a, era, r):
            out.append(f"   {era:9s} {lbl}")
            line = f"             LQ {fmt_range(tuple(lq))}   hard ops {fmt_range(tuple(t))}"
            if extra:
                line += "   " + ", ".join(f"{k}={v}" for k, v in extra.items())
            out.append(line)
    out.append("")

    out.append("EXPORTS  (per era: headline against the box, shots, wall, epsilon_l, "
               "the depth and factory keys of CONTRACT.md rule 12, the primitive breakdown)")
    for era, r in results.items():
        p = m.PUBLISHED[era]
        ok_lq = close(r.lq, p.lq, p.rel_tol)
        ok_t = p.hard_ops is None or close(r.hard_ops, p.hard_ops, p.rel_tol)
        flag = "ok" if (ok_lq and ok_t) else "MISMATCH"
        out.append(f"   {era}  [{flag}]  box: {p.src}  (rel_tol {p.rel_tol})")
        out.append(f"             lq            {fmt_range(r.lq):>18s}   box {fmt_range(p.lq)}")
        out.append(f"             hard_ops      {fmt_range(r.hard_ops):>18s}   box {fmt_range(p.hard_ops)}")
        out.append(f"             shots         {_val(r.shots):>18s}")
        out.append(f"             wall_time_s   {_val(r.wall_time_s):>18s}")
        out.append(f"             epsilon_l     {_val(r.epsilon_l):>18s}")
        for k in DEPTH_EXPORTS:
            if k in r.intermediates:
                out.append(f"             {k:13s} {_val(r.intermediates[k]):>18s}")
        if r.breakdown:
            out.append(f"             breakdown: {len(r.breakdown)} primitives, sum {r.breakdown_total():.4g} T")
            for q in r.breakdown:
                out.append(f"               {q.name:36s} {q.count:>10.4g} x {q.t_each:>8.4g} = {q.t_total:>10.4g}"
                           f"  {q.status.value}")
        for n in r.notes:
            out.append(f"             note: {n}")
        others = sorted(k for k in r.intermediates if k not in DEPTH_EXPORTS)
        if show_intermediates:
            out.append(f"             intermediates ({len(others)} more keys):")
            for k in others:
                out.append(f"               {k:50s} {_val(r.intermediates[k])}")
        else:
            out.append(f"             intermediates: {len(others)} more keys (--intermediates lists them)")
        out.append("")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="estimates")
    ap.add_argument("--resources", action="store_true", help="write resources.json")
    ap.add_argument("--status", action="store_true", help="write CIRCUIT_STATUS.md")
    ap.add_argument("--inputs", action="store_true", help="show every assumption with provenance")
    ap.add_argument("--ch", type=int, nargs="*", help="restrict to chapters")
    ap.add_argument("--chapter", type=_chapter_arg, metavar="chNN",
                    help="one chapter's assumptions, resources.json rows and exports (e.g. ch03)")
    ap.add_argument("--intermediates", action="store_true",
                    help="with --chapter: list every intermediate the model records")
    args = ap.parse_args(argv)
    if args.chapter is not None:
        print(chapter_report(args.chapter, args.intermediates))
        return
    chapters = args.ch or available()
    missing = [c for c in CHAPTERS if c not in chapters]
    if missing and not args.ch:
        print(f"(no model yet for chapters {missing})", file=sys.stderr)
    if args.resources:
        p = SCRIPTS / "resources.json"
        p.write_text(json.dumps(resources_json(chapters), indent=1))
        print(f"wrote {p}")
        return
    if args.status:
        p = DOCS / "CIRCUIT_STATUS.md"
        p.write_text(circuit_status_md(chapters))
        print(f"wrote {p}")
        return
    print(table(chapters, args.inputs))


if __name__ == "__main__":
    main()
